### ISSUE TITLE
Manage multiple servers through a single arkmanager.

### ISSUE THREAD

**Issue by N0F3X** [FezVrasta/ark-server-tools#62] opened 2015-06-26 18:31 UTC
It would be very nice if you could add an option to run multiple game servers and use only one arkmnanager.

**Comment by FezVrasta** [comment] 2015-06-26 19:15
Yes I think it would be very nice, it shouldn't be difficult to implement I think

**Comment by klightspeed** [comment] 2015-08-07 11:48
arkmanager supports this as of 562bb93.  However, the init scripts do not support it.
I think if we want the init scripts to support it, we'd need to add an autostart setting in arkmanager.cfg which lists which configs to autostart, and perhaps an autostart command in arkmanager to support it.

**Comment by FezVrasta** [comment] 2015-09-01 08:50
duplicate of #136

**Closed by FezVrasta** 2015-09-01 08:50 UTC
Labels: Enhancement
