### ISSUE TITLE
Upgrade trouble

### ISSUE THREAD

**Issue by tenten36** [FezVrasta/ark-server-tools#153] opened 2015-09-02 05:14 UTC
When I try to do

arkmanager upgrade

it says: 

arkmanager v1.2: Checking for updates...
/usr/local/bin/arkmanager: line 375: A new version was found! Do you want to upgrade ARK Server Tools to v${arkstLatestVersion}?: wrong variable

Did I do something wrong?

**Comment by klightspeed** [comment] 2015-09-02 05:54
This is a duplicate of #109

As a workaround, please try re-installing arkmanager as suggested in https://github.com/FezVrasta/ark-server-tools#install-ark-server-tools

**Comment by tenten36** [comment] 2015-09-02 06:05
I will re-install arkmanager although my .cfg is the actual one with the arkstVersion variable.

**Comment by klightspeed** [comment] 2015-09-14 22:20
The first issue (bad substitution) was fixed in the 1.3 release.  The second issue (unexpected operator) was fixed with hotfix commit 8a7f6d24bc2e4ac6dd6ddbc6aa97512e15e39450

**Closed** 2015-10-13 01:20 UTC
Labels: User feedback needed
