### ISSUE TITLE
[Small Bug ] arkmanager status

### ISSUE THREAD

**Issue by Betaman2k** [FezVrasta/ark-server-tools#32] opened 2015-06-21 12:46 UTC
Heya
OS: Debian 8 with 64 bit

First great script xD
second small bug, if u wanna use arkmanager status
u get this message
 Server running:  Yes
 Server online:   No   <<<<<<<   Server ist online and u can join the server
 Server version:  666499
regards
Betaman

**Comment by FezVrasta** [comment] 2015-06-21 15:11
duplicate of #31

**Closed by FezVrasta** 2015-06-21 15:11 UTC
