### ISSUE TITLE
status command seems not working

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/ark-server-tools#31] opened 2015-06-21 12:45 UTC
it returns always false even if the server is online.

**Comment by puseidr** [comment] 2015-06-21 15:12
the serverport is hardcoded in the script (7779) but the server is running on an other port..

it looks like the arkserveropts (?Port=$arkserverport) doesn't work

the function should be:
```bash
function isTheServerUp(){
  PORT=$arkserverport
  lsof -i |grep $PORT > /dev/null
  result=$?
  return $result
}

```


its crazy, i've set the serverport to "7777" in the arkmanager.cfg 
lsof -i says its running on 7779
and arkserver.net says its running on 7778
WTF?!

**Comment by Sispheor** [comment] 2015-06-21 15:29
Same for me

**Comment by Atriusftw** [comment] 2015-06-21 15:43
* Port not defined in launch options.
* lsof -i reports port 7778.
* Server browser reports 7777.
* Arkservers-met reports 7777.

**Comment by Sispheor** [comment] 2015-06-21 15:49
Same for me, port. If i check with "netstat -lputen" i can see the port is listenning on 7778. And it appear on 7777 on the steam server browser . And set the port in the command line seems to not change anything.
So wath the plan?

I purpose to tell our user to set the port in Ark settings and set the same port in arkmanager config to allow us to check the server is online.

**Comment by Sispheor** [comment] 2015-06-21 16:04
To check if is one line we have to check our local listenning port. Whatever the steam broswer say.

It's fixed in my last PR

**Comment by Atriusftw** [comment] 2015-06-21 18:00
"The inconsistancy is caused by the unreal engine and how it is setup. In the BaseEngine config file it has the ports set on a +1 offset of each other."

**Comment by pandabear41** [comment] 2015-06-21 18:29
Yeah as Atriusftw quoted from my post on steam community. From what I understand unreal engine has a public port and a peer port. The "Port" config option is what the server reports when the it communicates with steam through the steamapi. (ie hense why people get "STEAMPS3 - AsyncTCPSocket created" and "STEAMPS3 - AsncTCPSocket destroyed" errors)
The "PeerPort" is the actual port that the server is listening to. For the sake of is being confusing, I have set my Port and PeerPort in BaseEngine.ini to the exact same thing.

**Comment by Atriusftw** [comment] 2015-06-22 08:30
Im currently graphing the mentioned ports for results. Will post them when they're filled up.

**Comment by FezVrasta** [comment] 2015-06-22 09:30
[steam@ns322377 ~]$ lsof -i |grep 27016; echo $?
ShooterGa 30686 steam   11u  IPv4 1190052      0t0  UDP *:27016
0
[steam@ns322377 ~]$ lsof -i |grep 27015; echo $?
1

Looks like lsof returns `1` if nothing is found and `0` if foud.. should we fix the script?

**Comment by Atriusftw** [comment] 2015-06-22 10:21
Haha, that is so opposite of what it should be. Totally f*cks with my mind.

**Comment by Sispheor** [comment] 2015-06-22 11:41
The script work for me like that. Are you testing the dev1.1? I have fixed
this part. Now we get the port number from the configuration file. And its
7778 by default.

**Comment by Sispheor** [comment] 2015-06-22 16:58
So, the script is actualy working by default? No?

**Comment by Atriusftw** [comment] 2015-06-23 13:37
Not working in dev1.1, as the run function subtracts 1 from the port defined in config.

**Comment by FezVrasta** [comment] 2015-06-23 13:42
Correct me if I am wrong, we subtract one from the port because the server then starts on port+1 so we have to check port once the server is started, because it is listening on (port-1)+1

no?

**Comment by Sispheor** [comment] 2015-06-23 13:48
The port defined in the configuration file should be the one that is up
when the server is up.

Not working in dev1.1, as the run function subtracts 1 from the port
defined in config.

—
Reply to this email directly or view it on GitHub
<https://github.com/FezVrasta/ark-server-tools/issues/31#issuecomment-114506038>
.

**Comment by Atriusftw** [comment] 2015-06-23 13:48
Yes, that is correct @FezVrasta.
Unreal Engine is stupid like that.

Basically, Unreal Engine adds 1 to the specified port in our config.
What i find is funny though - in the server browser it still shows the port in the config.

**Comment by FezVrasta** [comment] 2015-06-23 13:51
I don't get where is the problem then

If we annul the Unreal Engine problem providing him `port-1` why should we check `port-1` when we look for the server status?

Unreal Engine has set the server to `(port-1)+1` (= `port`) so we should check `port`, and this is what we are currently doing in 1.1

**Comment by Sispheor** [comment] 2015-06-23 13:53
Absolutly. I don't get why you play with that port. It's simple. What you
get with netstat is what you have to set in the configuration file to check
it.

2015-06-23 15:51 GMT+02:00 Fez Vrasta <notifications@github.com>:

> I don't get where is the problem then
>
> If we annul the Unreal Engine problem providing him port-1 why should we
> check port-1 when we look for the server status?
>
> Unreal Engine has set the server to (port-1)+1 (= port) so we should
> check port, and this is what we are currently doing in 1.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FezVrasta/ark-server-tools/issues/31#issuecomment-114512981>
> .
>



-- 
*Nicolas MARCQ*

**Comment by FezVrasta** [comment] 2015-06-23 13:55
Looks like there is some confusion here...

**Comment by Betaman2k** [comment] 2015-06-23 16:49
Now all fine, u can closed the bug xD

**Comment by PhuriousGeorge** [comment] 2015-06-24 00:23
I don't understand how it's fine? I'm still showing as not online

**Comment by Sispheor** [comment] 2015-06-24 06:21
@FezVrasta So what the plan? I suggest the port in the cfg be the real one listtening on the server. And we remove math from the function. And we explain how to get the port for the first time to set it correctly in the cfg.

**Comment by FezVrasta** [comment] 2015-06-24 12:14
@Sispheor sorry I don't get what you mean, if we want the server to listen to the given port, we have to do math.

The problem with the command seems that it says always that the server is online even when not... (And I don't get why)

**Comment by FezVrasta** [comment] 2015-06-24 15:54
this is the latest issue before the 1.1 release.

on my machine everything seems good honestly.

**Comment by Sispheor** [comment] 2015-06-24 16:01
I will test in a few minutes on my Ubuntu and I'll give you a feedback if it's ok

**Comment by FezVrasta** [comment] 2015-06-24 16:04
@Sispheor we are going to merge a PR which replaces lsof with netstat, probably is better wait for it before test.

**Comment by Sispheor** [comment] 2015-06-24 16:10
I didn't use netstat because it seems to need root privilege to work. Are
you sure you can get the port as steam user with netstat?

2015-06-24 18:04 GMT+02:00 Fez Vrasta <notifications@github.com>:

> @Sispheor <https://github.com/Sispheor> we are going to merge a PR which
> replaces lsof with netstat, probably is better wait for it before test.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FezVrasta/ark-server-tools/issues/31#issuecomment-114926039>
> .
>



-- 
*Nicolas MARCQ*

**Comment by FezVrasta** [comment] 2015-06-24 16:15
It works with non root user, but the output is very different from BSD to Linux, I'm waiting to see what @klightspeed will push.

**Comment by Sispheor** [comment] 2015-06-24 18:35
The command works for me. But this is the output on Debian 8
```
steam@nas:~$ arkmanager status
 Server running:   Yes 
Utilisation : grep [OPTION]... MOTIF [FICHIER]...
Exécutez « grep --help » pour obtenir des renseignements complémentaires.
 Server online:   Yes 
 Server version:   666499
```

I have a tooltip about the use case of grep (in french sorry) in the middle of the output.

**Comment by FezVrasta** [comment] 2015-06-24 19:12
have you updated the configuration?

I had the same problem because my configuration was not updated (the port variable changed)

**Comment by Sispheor** [comment] 2015-06-24 19:25
Yep, I've updated it. I work on a fix for this issue. PR incoming.

2015-06-24 21:12 GMT+02:00 Fez Vrasta <notifications@github.com>:

> have you updated the configuration?
>
> I had the same problem because my configuration was not updated (the port
> variable changed)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FezVrasta/ark-server-tools/issues/31#issuecomment-114983991>
> .
>



-- 
*Nicolas MARCQ*

**Closed** 2015-06-24 20:46 UTC
Labels: bug

**Comment by Sispheor** [comment] 2015-06-24 20:50
Have you tested it? Ok for you @FezVrasta ?

**Comment by Atriusftw** [comment] 2015-06-25 04:20
Netstat only needs root privileges to show all active connections.
Can be run on normal user - shows their active connections.
