### ISSUE TITLE
update --update-mods       (Requires server restart?)

### ISSUE THREAD

**Issue by kyle142** [FezVrasta/ark-server-tools#382] opened 2016-02-04 01:18 UTC
Hello, this may be an issue on my end, or a problem with arkmanager?

When ever running the command arkmanager update --update-mods, the server will check for updates however even if there isn't a new version of the mods to download, It will still always restart the server time and time again.

**Comment by StevenB83** [comment] 2016-02-08 08:21
Hi,

I seem to have this issue as well when I updated to the latest 1.5 branch.
There doesn't seem to be any updates, but the new mod update method seems to force an update anyways.

[Spoiler]`Running command 'update' for instance 'vanilla'
Your server is already up to date! The most recent version is 965682.
Running command 'update' for instance 'valhalla'
Downloading mod 489596581 ... Mod 489596581 downloaded
Downloading mod 504122600 ... Mod 504122600 downloaded
Downloading mod 510590313 ... Mod 510590313 downloaded
Downloading mod 516096294 ... Mod 516096294 downloaded
Downloading mod 519998112 ... Mod 519998112 downloaded
Downloading mod 520879363 ... Mod 520879363 downloaded
Downloading mod 533175507 ... Mod 533175507 downloaded
Downloading mod 533828549 ... Mod 533828549 downloaded
Downloading mod 534952636 ... Mod 534952636 downloaded
Downloading mod 536247310 ... Mod 536247310 downloaded
Downloading mod 539464369 ... Mod 539464369 downloaded
Downloading mod 558651608 ... Mod 558651608 downloaded
Downloading mod 567659264 ... Mod 567659264 downloaded
Downloading mod 576504995 ... Mod 576504995 downloaded
Downloading mod 581683725 ... Mod 581683725 downloaded
Downloading mod 590665112 ... Mod 590665112 downloaded
Server oppdatering om 15 minutter.`[/Spoiler]
Steven.

**Comment by StevenB83** [comment] 2016-02-08 18:29
I can confirm that it indeed forces an update as the test server "updates" every 20 mins (cron job every 20 doing "arkmanager update --warn --saveworld --update-mods @all") also tried @valhalla for the valhalla instance, still forces update on the test server.

Steven

**Comment by StevenB83** [comment] 2016-02-08 22:34
I tested with those changes, it doesn't really change anything as the end outcome is the same.
It "updates" the files even if there are no updates

Doesn't it compare the newly downloaded mods to the existing mods before initiating a server update?
I don't see the reason for it having to copy all/any of the downloaded mods from staging directory to the server directory if there hasn't been any changes.
This causes the manager to shut down the server and replace all the mod files from staging directory to the server directory without any of them actually having been updated. (this happens every time the update script is called). Downloading them works fine, but the logic that verifies whether or not there has been an update is not working.

Downloading the mods seemed to take a very long time as well, this may be unrelated to the changes. I don't have time to test any more tonight myself, I will take a better look at the script after work tomorrow.

Steven.

**Comment by klightspeed** [comment] 2016-02-08 23:14
@StevenB83 the pull request hasn't been merged yet.  Try downloading the modified arkmanager script from a8e95f9 (https://raw.githubusercontent.com/FezVrasta/ark-server-tools/a8e95f9/tools/arkmanager) and test it

**Comment by StevenB83** [comment] 2016-02-08 23:20
I edited in the changes :p

**Comment by klightspeed** [comment] 2016-02-08 23:23
@StevenB83 So, the `doDownloadMod()` function should look like:

```
#
# Downloads a mod from the Steam workshop
#
doDownloadMod(){
  local modid=$1
  local modsrcdir="$steamcmdroot/steamapps/workshop/content/$mod_appid/$modid"
  local moddldir="$steamcmdroot/steamapps/workshop/downloads/$mod_appid"
  cd "$steamcmdroot"
  retries=10

  while true; do
    echo -n "Downloading mod $modid"
    runSteamCMDspinner +workshop_download_item $mod_appid $modid
    result=$?
    if [ $result -eq 0 ]; then
      break
    else
      echo
      if [ ! -d "$moddldir" ]; then
        echo "Mod $modid download failed"
        break
      fi
      (( retries = retries - 1 ))
      if (( retries <= 0 )); then
        echo "Retries exhausted"
      fi
      echo "Mod $modid not fully downloaded - retrying"
    fi
  done

  if [ -f "$modsrcdir/mod.info" ]; then
    echo "Mod $modid downloaded"
    return 0
  else
    echo "Mod $modid was not successfully downloaded"
    return 1
  fi
}

```

**Comment by StevenB83** [comment] 2016-02-08 23:26
this is mine:

`#
# Downloads a mod from the Steam workshop
#
doDownloadMod(){
  local modid=$1
  local modsrcdir="$steamcmdroot/steamapps/workshop/content/$mod_appid/$modid"
  local moddldir="$steamcmdroot/steamapps/workshop/downloads/$mod_appid"
  cd "$steamcmdroot"
  retries=10

  while true; do
    echo -n "Downloading mod $modid"
    runSteamCMDspinner +workshop_download_item $mod_appid $modid
    result=$?
    if [ $result -eq 0 ]; then
      break
    else
      echo
      if [ ! -d "$moddldir" ]; then
        echo "Mod $modid download failed"
        break
      fi
      (( retries = retries - 1 ))
      if (( retries <= 0 )); then
        echo "Retries exhausted"
      fi
      echo "Mod $modid not fully downloaded - retrying"
    fi
  done

  if [ -f "$modsrcdir/mod.info" ]; then
    echo "Mod $modid downloaded"
    return 0
  else
    echo "Mod $modid was not successfully downloaded"
    return 1
  fi
}`

**Comment by StevenB83** [comment] 2016-02-08 23:29
This is mine:

`#
# Downloads a mod from the Steam workshop
#
doDownloadMod(){
  local modid=$1
  local modsrcdir="$steamcmdroot/steamapps/workshop/content/$mod_appid/$modid"
  local moddldir="$steamcmdroot/steamapps/workshop/downloads/$mod_appid"
  cd "$steamcmdroot"
  retries=10

  while true; do
    echo -n "Downloading mod $modid"
    runSteamCMDspinner +workshop_download_item $mod_appid $modid
    result=$?
    if [ $result -eq 0 ]; then
      break
    else
      echo
      if [ ! -d "$moddldir" ]; then
        echo "Mod $modid download failed"
        break
      fi
      (( retries = retries - 1 ))
      if (( retries <= 0 )); then
        echo "Retries exhausted"
      fi
      echo "Mod $modid not fully downloaded - retrying"
    fi
  done

  if [ -f "$modsrcdir/mod.info" ]; then
    echo "Mod $modid downloaded"
    return 0
  else
    echo "Mod $modid was not successfully downloaded"
    return 1
  fi
}`

**Comment by StevenB83** [comment] 2016-02-08 23:31
also as I said, diff /home/steam/arkmanager /usr/local/bin/arkmanager showed no errors with the one you linked.

**Comment by klightspeed** [comment] 2016-02-09 12:21
If you apply the next two commits in #388, what is the output of:

```
arkmanager update @valhalla --update-mods --dots
```

BTW, to make the above code, use:
<pre>
```
your code...
```
</pre>

**Comment by StevenB83** [comment] 2016-02-09 21:26
Hi.
I wasn't able to test before now, but here goes!

`steam@ARK-Test:~$ arkmanager update @valhalla --update-mods --dots
Running command 'update' for instance 'valhalla'
Downloading mod 489596581 ...  ..........Mod 489596581 downloaded
Downloading mod 504122600 ...  ........Mod 504122600 downloaded
Downloading mod 510590313 ...  ........Mod 510590313 downloaded
Downloading mod 516096294 ...  ........Mod 516096294 downloaded
Downloading mod 519998112 ...  ........Mod 519998112 downloaded
Downloading mod 520879363 ...  ........Mod 520879363 downloaded
Downloading mod 533175507 ...  .........Mod 533175507 downloaded
Downloading mod 533828549 ...  .......Mod 533828549 downloaded
Downloading mod 534952636 ...  ..........Mod 534952636 downloaded
Downloading mod 536247310 ...  ........Mod 536247310 downloaded
Downloading mod 539464369 ...  ........Mod 539464369 downloaded
Downloading mod 558651608 ...  ........Mod 558651608 downloaded
Downloading mod 567659264 ...  ........Mod 567659264 downloaded
Downloading mod 576504995 ...  .......Mod 576504995 downloaded
Downloading mod 580718120 ...  .........Mod 580718120 downloaded
Downloading mod 581683725 ...  .......Mod 581683725 downloaded
Downloading mod 590665112 ...  ........Mod 590665112 downloaded
Your server is already up to date! The most recent version is 967620.`

`steam@ARK-Test:~$ arkmanager update @valhalla --update-mods --spinner
Running command 'update' for instance 'valhalla'
Downloading mod 489596581 ... Mod 489596581 downloaded
Downloading mod 504122600 ... Mod 504122600 downloaded
Downloading mod 510590313 ... Mod 510590313 downloaded
Downloading mod 516096294 ... Mod 516096294 downloaded
Downloading mod 519998112 ... Mod 519998112 downloaded
Downloading mod 520879363 ... Mod 520879363 downloaded
Downloading mod 533175507 ... Mod 533175507 downloaded
Downloading mod 533828549 ... Mod 533828549 downloaded
Downloading mod 534952636 ... Mod 534952636 downloaded
Downloading mod 536247310 ... Mod 536247310 downloaded
Downloading mod 539464369 ... Mod 539464369 downloaded
Downloading mod 558651608 ... Mod 558651608 downloaded
Downloading mod 567659264 ... Mod 567659264 downloaded
Downloading mod 576504995 ... Mod 576504995 downloaded
Downloading mod 580718120 ... Mod 580718120 downloaded
Downloading mod 581683725 ... Mod 581683725 downloaded
Downloading mod 590665112 ... Mod 590665112 downloaded
Your server is already up to date! The most recent version is 967620.`

Also my crontab ```*/20 * * * * /usr/local/bin/arkmanager update @valhalla --warn --saveworld --update-mods --backup > $HOME/ARK-Updatelogs/`date +\%Y-\%m-\%d-\%H-\%M`-cron.log 2>&1```

`steam@ARK-Test:~/ARK-Updatelogs$ tail -f 2016-02-09-22-20-cron.log
Downloading mod 504122600 ...  ........Mod 504122600 downloaded
Downloading mod 510590313 ...  .........Mod 510590313 downloaded
Downloading mod 516096294 ...  .........Mod 516096294 downloaded
Downloading mod 519998112 ...  ........Mod 519998112 downloaded
Downloading mod 520879363 ...  ........Mod 520879363 downloaded
Downloading mod 533175507 ...  ..........Mod 533175507 downloaded
Downloading mod 533828549 ...  ..............Mod 533828549 downloaded
Downloading mod 534952636 ...  .........Mod 534952636 downloaded
Downloading mod 536247310 ...  .........Mod 536247310 downloaded
Downloading mod 539464369 ...  ........Mod 539464369 downloaded
Downloading mod 558651608 ...  .........Mod 558651608 downloaded
Downloading mod 567659264 ...  ..........Mod 567659264 downloaded
Downloading mod 576504995 ...  .........Mod 576504995 downloaded
Downloading mod 580718120 ...  .........Mod 580718120 downloaded
Downloading mod 581683725 ...  .......Mod 581683725 downloaded
Downloading mod 590665112 ...  .......Mod 590665112 downloaded
Your server is already up to date! The most recent version is 967620.`

Everything seems to work beautifully! Thank you very much!
Neither the dots nor the new spinner forced an update of the mods. :+1: 
Also tested with the latest available via arkmanager upgrade-tools.

Steven.

**Comment by kyle142** [comment] 2016-02-09 22:36
Great thank you so much this will be a huge help. Can't wait till the next commit that reaches the main branch

**Comment by kyle142** [comment] 2016-02-15 00:08
So when can this fix be pushed to the main branch? It makes me a little nervous when i have to go to sleep as I can't keep the mods up to date on the server without restarts every check lol

**Comment by klightspeed** [comment] 2016-02-27 13:43
This should be in the master branch now.

**Closed** 2016-03-12 11:38 UTC
