### ISSUE TITLE
Whats wrong?

### ISSUE THREAD

**Issue by peterkristel** [FezVrasta/ark-server-tools#684] opened 2016-12-10 21:07 UTC
arkmanager install
Running command 'install' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
Installing ARK server ... \
Message from syslogd@server1 at Dec 10 22:09:34 ...
 sert_20161210220933_8.dmp[5721]: Finished uploading minidump (out-of-process): success = yes

Message from syslogd@server1 at Dec 10 22:09:34 ...
 sert_20161210220933_8.dmp[5721]: response: Discarded=1

Message from syslogd@server1 at Dec 10 22:09:34 ...
 sert_20161210220933_8.dmp[5721]: file ''/tmp/dumps/assert_20161210220933_8.dmp'', upload yes: ''Discarded=1''                                                                                                                              \
Message from syslogd@server1 at Dec 10 22:09:44 ...
 sert_20161210220943_7.dmp[5769]: Finished uploading minidump (out-of-process): success = yes

Message from syslogd@server1 at Dec 10 22:09:44 ...
 sert_20161210220943_7.dmp[5769]: response: Discarded=1

Message from syslogd@server1 at Dec 10 22:09:44 ...
 sert_20161210220943_7.dmp[5769]: file ''/tmp/dumps/assert_20161210220943_7.dmp'', upload yes: ''Discarded=1''

**Comment by peterkristel** [comment] 2016-12-10 21:55
ark@server1:~$ arkmanager install
Running command 'install' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
Installing ARK server ... \

**Comment by klightspeed** [comment] 2016-12-11 12:31
Duplicate of #681

**Closed by klightspeed** 2016-12-11 12:31 UTC
