### ISSUE TITLE
Update download interrupted

### ISSUE THREAD

**Issue by cronner** [FezVrasta/ark-server-tools#503] opened 2016-06-07 22:09 UTC
Getting last hours:

Downloading ARK update ... Update download interrupted

with --verbose i can see it's stuck at:
Update state (0x61) downloading, progress: 79.27 (274934996 / 346819760)

plenty of hdd storage available

**Comment by klightspeed** [comment] 2016-06-08 04:18
This appears to be a duplicate of #502

**Comment by klightspeed** [comment] 2016-06-08 16:54
@cronner Is this resolved?

**Comment by cronner** [comment] 2016-06-08 16:56
Yes I think it was Steam releated? seems to update fine again

**Closed** 2016-06-08 16:56 UTC
